version: "3.3"

networks:
  mynet:

volumes:
  db-v:

services:
  db:
    image: mysql
    container_name: db-c
    volumes:
      - db-v:/var/lib/mysql
    restart: always
    env_file:
      - ./env/db.env
    networks:
      - mynet

  phpmyadmin:
    image: phpmyadmin
    container_name: admin-c
    depends_on:
      - db
    ports:
      - 8081:80
    env_file:
      - ./env/db.env
    networks:
      - mynet

  php-app:
    build:
      context: ./php/
      dockerfile: ./docker/Dockerfile
    container_name: php-c
    depends_on:
      - db
    env_file:
      - ./env/php.env
      - ./env/db.env
    volumes:
      # bind mount
      - ./php/:/var/www/html/api
    ports:
      - "80:80"
    networks:
      - mynet
